### ISSUE TITLE
Section 2.4: the 2x2 matrix multiplication does not render properly in html even though it renders properly in markdown.

### ISSUE THREAD

**Issue by flighttestfact** [Society-of-Flight-Test-Engineers/handbook-2013#169]

**Comment by cooknl** [comment]
I'll look at it

**Comment by cooknl** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/5116899/76106007-06b4aa00-5fa4-11ea-942d-d90584751605.png)

**Comment by cooknl** [comment]
It was the extra new lines between the elements that was the problem.
