### ISSUE TITLE
Where did \omega come from on page 6-4?

### ISSUE THREAD

**Issue by flighttestfact** [Society-of-Flight-Test-Engineers/handbook-2013#191]
Also, as I edit the markdown I see three graphics:
06005
06006
06007

I think one graphic is a graphic and the other two are equations...how do I figure out which is which?

**Comment by cooknl** [comment]
Pretty sure that should be "w", the vertical velocity, as in [u,v,w]

**Comment by flighttestfact** [comment]
That's what I thought. Thanks for checking.

**Comment by cooknl** [comment]
Regarding the graphics, scroll to the bottom of the file, where the image links are defined.

docs/media/06/ is the directory to find the image files.

Svg files can be opened in your browser.
