### ISSUE TITLE
Explain notation on bottom of page 06-9

### ISSUE THREAD

**Issue by flighttestfact** [Society-of-Flight-Test-Engineers/handbook-2013#205]
The left hand side of the bottom three equations has a fraction inside of brackets, and two numbers floating on the right side of the closing bracket.  

What is meant by this notation?

**Comment by cooknl** [comment]
I'm unfamiliar with this notation.

**Comment by cooknl** [comment]
"H" isn't defined in the section, either.

**Comment by cooknl** [comment]
H is defined as angular momentum in 1.8 Mechanics Relations.

Specific angular momentum is a hard thing to track down on the interwebs.

I found a discussion of reference frame transformations here, though:
http://www.stengel.mycpanel.princeton.edu/MAE331Lecture10.pdf slide 40

There is similar notation, that indicates the transform is FROM the frame of reference annotated by the lower symbol TO the frame of reference annotated by the upper symbol.

I still don't know what "a, n, l, y, and k" indicate in this context, though.

I think a better source is Al's Math and Physics for Flight Testers available here:
https://www.ntps.edu/images/stories/documents/Vol._01_Math__Physics_for_Flight_Testers.zip

Section 7, pp. 7-19 and 7.20.

**Comment by markjonesjr** [comment]
Replying so you know I'm tracking these responses.

For now, we could remove those four lines.  Thoughts?

**Comment by flighttestfact** [comment]
I think they break it down into its three components, because a cross
product in 3 space results in 3-vector.

**Comment by cooknl** [comment]
I suggest lifting the equations from Al's product, as it looks like the
source material.

**Comment by flighttestfact** [comment]
I see that Al's product doesn't use the wacky notation.

**Comment by cooknl** [comment]
Yeah, it makes a lot more sense to me.
