### ISSUE TITLE
Subscript "0" or "o"?

### ISSUE THREAD

**Issue by rwstanfo** [Society-of-Flight-Test-Engineers/handbook-2013#210]
I have seen multiple cases where subscripts that I typically think of as "zero" (such as CD_{**0**}... "C-D nought") have been written with a lower-case letter "o" (CD_o).  I'm thinking this may be a carry-over from writing formulas with typewriters and physically adjusting the page and using the smaller "o" for subscripts.  An example of this is on page 05-12 for Sutherland's law.  Where I'm finding these cases, I am replacing them with subscript zeros.  I'm not missing something important here, am I @cooknl & @flighttestfact ?

**Comment by cooknl** [comment]
I'm 1oo% on board. Certainly good the ones you find. Please keep this issue open, though, and I'll do a "sweep" through all.

VS Code has a super sweet "global search and replace" that can use regular expressions to ferret out these kinds of things.

**Comment by markjonesjr** [comment]
I'm 0n b0ard t00

**Comment by rwstanfo** [comment]
Thank y0u!

**Comment by cooknl** [comment]
I'm about to do this sweep. I'll note that one of the instances of "o" was for an "oscillation" subscript...but I think it's the exception that proves the rule.

**Comment by cooknl** [comment]
BTW, this is the "global" search function, including seeing each individual line of results in the editor, in VS Code
![image](https://user-images.githubusercontent.com/5116899/79278879-53788400-7e72-11ea-8a05-3e7f74ceecc7.png)
