### ISSUE TITLE
Equation Missing

### ISSUE THREAD

**Issue by johnhed2** [Society-of-Flight-Test-Engineers/handbook-2013#211]
Second group of equations in Section 6.2.2 seems to be missing a "y" equation.

**Comment by cooknl** [comment]
I see what you mean! @johnhed2

**Comment by johnhed2** [comment]
Thanks

**Comment by flighttestfact** [comment]
This matches the current handbook.

**Comment by flighttestfact** [comment]
If you read the text and look at the equations you see only sign changes (positive to negative) in the two equations. The y equation does not change.

**Comment by cooknl** [comment]
Thanks for your attention!

This was part example and part honest question.

Concur.

**Comment by flighttestfact** [comment]
Really grateful for your leadership AND service to the TC members in this
project.  I was delighted to see John creating issues and doing
proofreading.

**Comment by johnhed2** [comment]
Old dog, new tricks !!!   =:-O

**Comment by cooknl** [comment]
Speaking of new tricks

`:astonished:` -> :astonished:

https://gist.github.com/rxaviers/7360908
