### ISSUE TITLE
Section 2.4.1 matrix addition

### ISSUE THREAD

**Issue by AIrbusjim** [Society-of-Flight-Test-Engineers/handbook-2013#232]
I believe the lower right hand entry in the result matrix should be a21b12+a22b22 (and not a21b12+a22b12 as is written).

**Comment by flighttestfact** [comment]
You are on a roll! Thanks so much for all the input. I will take a look ASAP, because I have the next three days off.

**Comment by flighttestfact** [comment]
Jim, can you confirm that this was from the Matrix Multiplication example? The title is misleading.

**Comment by AIrbusjim** [comment]
Hello
Yes, my mistake in the title of the issue, it is indeed for matrix multiplication.
Sorry about that,

Jim FAWCETT CEng
Lead Flight Test Engineer
Flight Operations - IVTS
AIRBUS

Phone: +33 (0)5 82 05 10 95
Mobile: +33 (0)6 38 76 97 81
Fax: +33 (0)5 61 93 29 34
Mailto:james.fawcett@airbus.com<mailto:james.fawcett@airbus.com>

Airbus S.A.S.
2 rond-point Emile Dewoitine
31700 Blagnac
France
