### ISSUE TITLE
Conventions for Positive Control Surface Deflections LEF copy/paste error

### ISSUE THREAD

**Issue by cooknl** [Society-of-Flight-Test-Engineers/handbook-2013#300]
LEF have "c", presumably a copy/paste error from canards

**Comment by cooknl** [comment]
Also, what does it mean for a LEADING edge flap to have TRAILING edge down?!?!?

**Comment by cooknl** [comment]
The issue goes all the way back to the 2001 original version.

**Comment by pavitsas** [comment]
Agree, for LEFs, c should be replaced with lef, and TED should be replaced maybe with "Extended"? I think both these terms were copy/paste from canards.
What looks a little strange to have in that row is "differential". Are there really any differential LEFs? Or is this just a line repetition from other surfaces...?

**Comment by cooknl** [comment]
I'll have a look for F-16 on the differential question.

I do know that the F-16 LEFs have a range of motion that includes "leading edge above chord line" as well as "leading edge below chord line"

**Comment by cooknl** [comment]
F-16 explicitly prevents LEF asymmetry. I believe that would be the general case, as well, so differential LEF is silly.

Leading edge up or down should be the direction, as well.
