### ISSUE TITLE
Initial comments on Chapter 3

### ISSUE THREAD

**Issue by pavitsas** [Society-of-Flight-Test-Engineers/handbook-2013#301]
This is my first opening of an issue, trying to understand how everything works.

I had a quick look into Chapter 3 and have some comments for editing:

- [x] Ambient density symbol should be ρ instead of rho
- [x] Section 3.1: Avogardo constant symbol should be N_A instead of N_0
- [ ] In paragraph “Gravity Influence on Aircraft Cruise Performance”, there seems that "i" subscripts should be "t(est)" subscripts.
   - [x] parameters C_L, C_D should be written in math characters
   - [x] CLi should be CLt
   - [ ] the ω in Ν_z does not have any meaning for me, I think it needs to be removed. Also Nzωi should be Nzt
   - [x] ARe in second equation should be in math characters
   - [x] Wfi Should be Wft

**Comment by cooknl** [comment]
Panos, thank you for the new Issue! The nice thing about this process is that the feedback won't get lost in someone's e-mail inbox.

I look forward to working through these.

**Comment by cooknl** [comment]
@pavitsas regarding the ambient density, isn't ρ the symbol for rho? Can you elaborate?

**Comment by pavitsas** [comment]
@cooknl it is! My concern is that "rho" is not a symbol used in equations, but a symbol description, so it should be replaced with ρ in the "Symbols" column. In the last line of the table ρ and not rho is used to define σ.

**Comment by cooknl** [comment]
Ah! Now I see it.

**Comment by cooknl** [comment]
It was a case of a missing backslash
`\(\rho\)` produces ρ
`\(rho\)` produces `rho`

**Comment by cooknl** [comment]
I blame "i" for "t" on old man eyes.

**Comment by cooknl** [comment]
The omega is in the original 2013 version, so I'll have to open a separate issue.
