### ISSUE TITLE
? - Section 1.2 Greek alphabet

### ISSUE THREAD

**Issue by flighttestfact** [Society-of-Flight-Test-Engineers/handbook-2013#58]
This is a QUESTION, but I didn't know how to assign a note to someone.

Do we want to add the LaTeX command for every greek letter, like \Alpha?
Do we want to add a note at the bottom of the table that describes the general format for the LaTeX command?
Do we want to add a header to the table column specifying "LaTeX command"?

**Comment by cooknl** [comment]
Good questions. I'm open to input from the Council, too.

**Comment by cooknl** [comment]
1. Uppercase greek letters that have English equivalents don't have a "spelled out" LaTeX code. "A" is `A`
2. I think the pattern is clear without a note
3. I'll add the column header
