### ISSUE TITLE
Preface - 2013 issue?

### ISSUE THREAD

**Issue by AIrbusjim** [Society-of-Flight-Test-Engineers/handbook-2013#63]
The preface talks about the 2013 issue but surely this will become the 2020 issue? And you will be rightfully mentioned as the editor for the post 2013 period?

**Comment by cooknl** [comment]
The original intent was a "direct port" of the 2013 version, followed by an
"optimized" version.

That plan may or may not survive initial contact with "the enemy" (enemy =
reality)

My contributions are captured by the GitHub history, but yes, I intend to
mark my editorship.

Thanks, Jim!
