### ISSUE TITLE
Section 18 author

### ISSUE THREAD

**Issue by AIrbusjim** [Society-of-Flight-Test-Engineers/handbook-2013#64]
Al Lawless is listed as the author for section 18 but, assuming this is going to be based on the document which I contributed last year, I would like to be recognised as the author please!
Thanks, Jim FAWCETT

**Comment by cooknl** [comment]
Thanks, Jim!

**Comment by cooknl** [comment]
Jim, I believe you are conflating the Section 18 (Telemetry Control Room and Radio Communications) for the Section 20 addendum (Communication Systems Testing).

**Comment by AIrbusjim** [comment]
It wasn't clear when I made the comment, but now the markdown conversion is complete then I can see that the section 20 is attributed to me, so all is in order.

**Comment by cooknl** [comment]
Wonderful!
