### ISSUE TITLE
Provide figure and table labels that can be referenced

### ISSUE THREAD

**Issue by rwstanfo** [Society-of-Flight-Test-Engineers/handbook-2013#69]
Seeing inconsistencies with how figures are labeled (if at all) and non-descriptive references in the text (i.e. "see flowchart" … when the flowchart doesn't appear until several pages later).  Can the markdown be set up to handle figure, equation, and section labels and inner-document referencing?

**Comment by cooknl** [comment]
Short answer is yes.

I have not been doing it a lot, yet.

https://bookdown.org/yihui/bookdown/cross-references.html

**Comment by rwstanfo** [comment]
Thanks.  Any concerns about incorporating cross-referencing?  Otherwise I'll try to start rolling it in.

**Comment by cooknl** [comment]
None.

As you get the swing of it, please note if there are any style pointers
that should be included in the wiki.
