### ISSUE TITLE
Missing figure files in Section 4.8

### ISSUE THREAD

**Issue by rwstanfo** [Society-of-Flight-Test-Engineers/handbook-2013#71]
The first two figures of Section 4.8 (delta Hpc vs V and delta Vpc vs V) are missing from the source data.  @cooknl are you able to locate these from the pandoc conversion?

**Comment by cooknl** [comment]
Yes. Assign the issue to me and I'll fix it this weekend.

**Comment by cooknl** [comment]
This was more difficult than I expected. Ended up copying from Word, pasting into PowerPoint, right-click "Save as Picture" to .svg, then manually moving into media folder and typing in references in Rmd.
