### ISSUE TITLE
03.05 Sea States

### ISSUE THREAD

**Issue by cooknl** [Society-of-Flight-Test-Engineers/handbook-2013#78]

**Comment by flighttestfact** [comment]
This isn't really a 3.05 question, but it applies to all of 3...did you put code for a "Table of Contents" on the first page of section 3 or just manually create the list of contents?

**Comment by cooknl** [comment]
That was a straight copy from the word document, which had been manually
done originally.

I've been removing them, given the HTML sidebar TOC

**Comment by flighttestfact** [comment]
Awesome. Thanks.
